name: Pages

on:
  push:
    branches:
      - v2 # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run webpack-build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          folder: dist
          branch: gh-pages
      - name: Release
        run: yarn vercel
      - name: Get the Ref
        id: get-ref
        uses: ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          path: 'dist'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          tag: "Web-${{ steps.get-ref.outputs.tag }}"
          body: "Auto upload ${{ github.ref }}"
          token: ${{ secrets.ACCESS_TOKEN }}
